Lab3
Keytus/Audio-Library pull request #2
Opened 2022-04-21 20:49 UTC by Keytus

2022-04-25 09:38 UTC, Nastik1811 reviewed
@Keytus 🤔 
<img width="763" alt="image" src="https://user-images.githubusercontent.com/37243282/165063162-26f3e7ed-3e8a-42a8-bd2d-9dec269acee5.png">

2022-04-27 10:07 UTC, Keytus commented
Fixed.Could you check it, please?

2022-04-28 08:02 UTC, Nastik1811 commented
Something wrong with mobile version
<img width="558" alt="image" src="https://user-images.githubusercontent.com/37243282/165706073-6b5c1b56-9449-4630-8b01-72a0d7aae206.png">

2022-04-28 08:48 UTC, Nastik1811 commented
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37243282/165714633-8fb97047-091c-48f9-b7b0-318b7f6af5d3.png">

2022-04-28 08:50 UTC, Nastik1811 requested changes
There is still something wrong with your styles

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +            var canClose = false;
Don't use `var`.

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +                    <figure type="button" class="audio-item" onclick="openForm('PlayerForm')">
` type="button" `? I don't remember this attribute on `figure`.

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +                    <figure type="button" class="audio-item" onclick="openForm('PlayerForm')">
I also think it was a doubtful idea to use figure in the way you did
<img width="730" alt="image" src="https://user-images.githubusercontent.com/37243282/165711427-985a8912-8180-43e3-9abd-6bd1bac22c03.png">

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +                </form>
Why have you wrapped this in `form`?

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +    <div id="page" style="height: inherit;" onclick="closeCurrentForm()">
`style="height: inherit;` ?

2022-04-28 08:50 UTC, Nastik1811 commented on index.html
> +    <div id="page" style="height: inherit;" onclick="closeCurrentForm()">
Why do you need inline styles here?

2022-04-28 08:50 UTC, Nastik1811 commented on common.blocks/desktop/popup/login-form/login-form.css
> +}
You have the same styles for .sign-up form. It's better to use common class to style them (btw, you have no reason to set absolute height for them)

2022-04-28 08:50 UTC, Nastik1811 commented on common.blocks/desktop/popup/add-form/add-top/add-top.css
> +    height: 40;
what about units?

2022-04-28 08:50 UTC, Nastik1811 commented on common.blocks/desktop/popup/add-form/add-bottom/add-bottom.css
> +    min-height: 330px;
`min-height` has no sense, since `height` set absolutely

2022-04-28 08:50 UTC, Nastik1811 commented on common.blocks/desktop/footer/footer.css
> +    width: 1440px;
you should not use absolute width/height for full-width/height containers

2022-04-28 15:59 UTC, Keytus commented
Remove var,remove type="button" from figures and buttons, unwraped buttons from form, remove inline styles, replace .sign-up and .login forms with .auth form, remove redundant size properties. Mobile version: it activated when device width 360px or less. Figures: i just wanna unite .mp3 image and .mp3 info as logically indivisible unit of content.

2022-04-30 09:18 UTC, Nastik1811 commented on index.html
> +            canClose = false;
![image](https://user-images.githubusercontent.com/37243282/166099747-d239ab0c-bb38-4a22-b6e5-de09ac3fb317.png)

2022-04-30 09:23 UTC, Nastik1811 commented on index.html
> +            canClose = false;
<img width="853" alt="image" src="https://user-images.githubusercontent.com/37243282/166099907-d44c13dd-b4f1-45bf-851a-be80ca008103.png">

2022-04-30 09:32 UTC, Nastik1811 approved these changes
You should use `let` or `const` in your js

For this work you get `7`

2022-04-30 11:04 UTC, merged